# Generated by Django 5.2.4 on 2025-07-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation_duration_reservation_recurrence_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='#808080', help_text='Enter hex color code, e.g., #FF5733', max_length=7),
        ),
    ]
