# Generated by Django 5.2.4 on 2025-07-05 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_room_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('rsvp_status', models.CharField(choices=[('NEEDS_ACTION', 'Needs Action'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TENTATIVE', 'Tentative')], default='NEEDS_ACTION', max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='booking.reservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reservation', 'email')},
            },
        ),
    ]
